"""`etoro-tui setup` — interactive wizard for first-time configuration.

Walks the user through:
  1. Generating eToro API keys (instructions only — opens nothing in the
     browser to keep dependencies zero).
  2. Pasting Public Key + User Key.
  3. Optionally writing them to ~/.etoro-tui/.env (chmod 600).
  4. Optionally seeding ~/.etoro-tui/config.toml from the example.

Designed to be safe on re-runs: existing files prompt for overwrite.
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

from . import config

_DOCS_CONFIG_EXAMPLE = (
    Path(__file__).resolve().parent.parent.parent / "docs" / "config.example.toml"
)


def _print_banner() -> None:
    print()
    print("=" * 60)
    print("  etoro-tui — first-time setup")
    print("=" * 60)
    print()


def _print_step(n: int, title: str) -> None:
    print(f"[{n}] {title}")
    print("-" * 60)


def _yes(prompt: str, default: bool = True) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "
    try:
        ans = input(prompt + suffix).strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return False
    if not ans:
        return default
    return ans.startswith("y")


def _prompt_secret(label: str) -> str:
    """Read a key from the user. Doesn't hide the input — these are
    moderate-sensitivity API tokens that the user is about to write to a
    file anyway, and getpass behaves badly inside some terminals."""
    while True:
        try:
            v = input(label).strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return ""
        if v:
            return v
        print("  (empty input — try again)")


def _walk_through_api_setup() -> None:
    print("eToro Public API keys come from your eToro account settings.")
    print()
    print("  1. Log in at  https://www.etoro.com")
    print("  2. Settings  →  Trading  →  API Key Management")
    print("  3. 'Create New Key'  →  permission: 'Read' (etoro-tui never sends")
    print("                         trade orders — Read is sufficient and safer)")
    print("  4. Copy BOTH keys immediately — eToro shows the user-key only once.")
    print()
    input("Press Enter when you have both keys handy… ")
    print()


def _write_envfile(public_key: str, user_key: str) -> Path:
    """Write keys to ~/.etoro-tui/.env with mode 0o600 atomically.

    Uses os.open(O_CREAT|O_WRONLY|O_TRUNC, mode=0o600) so the file is created
    with the restricted mode in a single syscall — closes the brief TOCTOU
    window where write_text() + chmod() left it momentarily at 0o644 (the
    default umask), during which a malicious local process could read it.

    On Windows the `mode` arg is largely ignored (NTFS doesn't honour POSIX
    bits); document this limitation in SECURITY.md rather than pretend to
    handle it.
    """
    config.ensure_home_secure()
    body = (
        "# Generated by `etoro-tui setup` — mode 0o600.\n"
        "# Add these to your shell profile if you prefer environment-only.\n"
        f"ETORO_PUBLIC_KEY={public_key}\n"
        f"ETORO_USER_KEY={user_key}\n"
    )
    flags = os.O_CREAT | os.O_WRONLY | os.O_TRUNC
    fd = os.open(config.ENV_FILE, flags, mode=0o600)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(body)
    except Exception:
        # If anything goes wrong mid-write, fdopen close handles fd cleanup.
        raise
    # Re-chmod in case the file pre-existed at a looser mode (O_CREAT honours
    # `mode` only for new files; existing files keep their old permissions).
    try:
        os.chmod(config.ENV_FILE, 0o600)
    except OSError:
        pass
    return config.ENV_FILE


def _seed_config_toml() -> Path | None:
    """Copy docs/config.example.toml → ~/.etoro-tui/config.toml if absent."""
    if config.CONFIG_TOML.exists():
        return None
    if not _DOCS_CONFIG_EXAMPLE.exists():
        return None
    config.ensure_home_secure()
    shutil.copy(_DOCS_CONFIG_EXAMPLE, config.CONFIG_TOML)
    return config.CONFIG_TOML


def _choose(prompt: str, options: list[str]) -> str | None:
    """Prompt for one of `options` (case-insensitive). None on abort."""
    bracket = "/".join(o.upper() for o in options)
    while True:
        try:
            ans = input(f"{prompt} [{bracket}]: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print()
            return None
        if not ans:
            return options[0]
        if ans in options:
            return ans
        print(f"  (please enter one of: {', '.join(options)})")


def run_setup() -> int:
    _print_banner()

    # Detect existing creds — and offer the right choice depending on intent.
    pk: str | None = None
    uk: str | None = None
    reuse = False
    try:
        existing_pk, existing_uk = config.get_credentials()
        existing_source = config.get_credentials_source()
        print(f"You already have credentials configured (source: {existing_source}).")
        print()
        print("  1. Keep current keys, change where they're stored")
        print("  2. Replace with NEW keys (rotated / different account)")
        print("  3. Cancel — leave everything as-is")
        print()
        choice = _choose("Choose", ["1", "2", "3"])
        print()
        if choice in (None, "3"):
            print("No changes made. Bye!")
            return 0
        if choice == "1":
            pk, uk = existing_pk, existing_uk
            reuse = True
            print(f"  ✓ Reusing existing keys (pk starts {pk[:6]}…, uk starts {uk[:6]}…)")
            print()
        # choice == "2" → fall through to the rotate flow
    except config.AuthMissingError:
        pass

    if not reuse:
        _print_step(1, "Get your eToro API keys")
        _walk_through_api_setup()

        _print_step(2, "Paste your keys")
        pk = _prompt_secret("  Public Key:  ")
        if not pk:
            print("Aborted.", file=sys.stderr)
            return 1
        uk = _prompt_secret("  User Key:    ")
        if not uk:
            print("Aborted.", file=sys.stderr)
            return 1
        print()

    _print_step(3, "Where to store them")
    print("  A.  ~/.etoro-tui/.env  (chmod 600). Cross-platform, simple file.")
    if config.keyring_available():
        print("  B.  System keyring  (macOS Keychain / Windows Credential Manager")
        print("                       / Linux Secret Service). Most secure.")
    else:
        print("  B.  System keyring  (NOT AVAILABLE — install with:")
        print("                       `pipx inject etoro-tui keyring` or")
        print("                       `pip install etoro-tui[keyring]`)")
    print("  C.  Just print export commands. You set the env vars yourself.")
    print()
    options = ["a", "c"]
    if config.keyring_available():
        options.insert(1, "b")
    choice = _choose("Choose", options)
    if choice is None:
        return 1
    print()

    # Belt-and-braces: by this point pk/uk are guaranteed non-None (the
    # earlier flow returns 1 if either is empty), but pyright can't prove it.
    assert pk is not None and uk is not None

    if choice == "a":
        path = _write_envfile(pk, uk)
        print(f"  ✓ Wrote {path} (mode 600)")
    elif choice == "b":
        try:
            config.keyring_save(pk, uk)
        except Exception as e:  # noqa: BLE001 — keyring backends raise diverse errors
            print(f"  ✗ Keyring save failed: {e}", file=sys.stderr)
            print("    Falling back to ~/.etoro-tui/.env")
            path = _write_envfile(pk, uk)
            print(f"  ✓ Wrote {path} (mode 600)")
        else:
            print("  ✓ Saved to system keyring (service: etoro-public-key /")
            print("    etoro-user-key, account: etoro-api)")
    else:  # choice == "c"
        print("  Add to your shell profile (~/.zshrc or ~/.bashrc):")
        print(f'    export ETORO_PUBLIC_KEY="{pk}"')
        print(f'    export ETORO_USER_KEY="{uk}"')
        print("  Then `source ~/.zshrc` (or open a new shell).")
    print()

    _print_step(4, "Seed a TOML config (optional)")
    print("  ~/.etoro-tui/config.toml lets you customise the indices list,")
    print("  point at local data sources, and tune refresh cadences.")
    print()
    if _yes("Seed it from docs/config.example.toml?", default=True):
        seeded = _seed_config_toml()
        if seeded is not None:
            print(f"  ✓ Wrote {seeded}")
        elif config.CONFIG_TOML.exists():
            print(f"  (already exists — left alone) {config.CONFIG_TOML}")
        else:
            print("  (example template not found — skipped)")
    print()

    print("=" * 60)
    print("  Done. Run `etoro-tui` to launch.")
    print("  Tip: `etoro-tui --demo` shows the UI without any API call.")
    print("=" * 60)
    return 0
