"""`etoro-tui setup` — interactive wizard for first-time configuration.

Walks the user through:
  1. Generating eToro API keys (instructions only — opens nothing in the
     browser to keep dependencies zero).
  2. Pasting Public Key + User Key.
  3. Optionally writing them to ~/.etoro-tui/.env (chmod 600).
  4. Optionally seeding ~/.etoro-tui/config.toml from the example.

Designed to be safe on re-runs: existing files prompt for overwrite.
"""
from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

from . import config


_DOCS_CONFIG_EXAMPLE = (
    Path(__file__).resolve().parent.parent.parent / "docs" / "config.example.toml"
)


def _print_banner() -> None:
    print()
    print("=" * 60)
    print("  etoro-tui — first-time setup")
    print("=" * 60)
    print()


def _print_step(n: int, title: str) -> None:
    print(f"[{n}] {title}")
    print("-" * 60)


def _yes(prompt: str, default: bool = True) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "
    try:
        ans = input(prompt + suffix).strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return False
    if not ans:
        return default
    return ans.startswith("y")


def _prompt_secret(label: str) -> str:
    """Read a key from the user. Doesn't hide the input — these are
    moderate-sensitivity API tokens that the user is about to write to a
    file anyway, and getpass behaves badly inside some terminals."""
    while True:
        try:
            v = input(label).strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return ""
        if v:
            return v
        print("  (empty input — try again)")


def _walk_through_api_setup() -> None:
    print("eToro Public API keys come from your eToro account settings.")
    print()
    print("  1. Log in at  https://www.etoro.com")
    print("  2. Settings  →  Trading  →  API Key Management")
    print("  3. 'Create New Key'  →  set permission to 'Read' (or 'Write' for trades)")
    print("  4. Copy BOTH keys immediately — eToro shows the user-key only once.")
    print()
    input("Press Enter when you have both keys handy… ")
    print()


def _write_envfile(public_key: str, user_key: str) -> Path:
    config.ETORO_TUI_HOME.mkdir(parents=True, exist_ok=True)
    config.ENV_FILE.write_text(
        f"# Generated by `etoro-tui setup` — chmod 600.\n"
        f"# Add these to your shell profile if you prefer environment-only.\n"
        f"ETORO_PUBLIC_KEY={public_key}\n"
        f"ETORO_USER_KEY={user_key}\n"
    )
    try:
        os.chmod(config.ENV_FILE, 0o600)
    except OSError:
        pass
    return config.ENV_FILE


def _seed_config_toml() -> Path | None:
    """Copy docs/config.example.toml → ~/.etoro-tui/config.toml if absent."""
    if config.CONFIG_TOML.exists():
        return None
    if not _DOCS_CONFIG_EXAMPLE.exists():
        return None
    config.ETORO_TUI_HOME.mkdir(parents=True, exist_ok=True)
    shutil.copy(_DOCS_CONFIG_EXAMPLE, config.CONFIG_TOML)
    return config.CONFIG_TOML


def run_setup() -> int:
    _print_banner()

    # Detect existing creds — env or file.
    try:
        existing_pk, _ = config.get_credentials()
        print(f"You already have credentials configured ({config.get_credentials_source()}).")
        if not _yes("Overwrite them?", default=False):
            print("Keeping existing setup. Bye!")
            return 0
        print()
    except config.AuthMissingError:
        pass

    _print_step(1, "Get your eToro API keys")
    _walk_through_api_setup()

    _print_step(2, "Paste your keys")
    pk = _prompt_secret("  Public Key:  ")
    if not pk:
        print("Aborted.", file=sys.stderr)
        return 1
    uk = _prompt_secret("  User Key:    ")
    if not uk:
        print("Aborted.", file=sys.stderr)
        return 1
    print()

    _print_step(3, "Where to store them")
    print("  A.  ~/.etoro-tui/.env  (chmod 600). Cross-platform, simple file.")
    if config.keyring_available():
        print("  B.  System keyring  (macOS Keychain / Windows Credential Manager")
        print("                       / Linux Secret Service). Most secure.")
    else:
        print("  B.  System keyring  (NOT AVAILABLE — install with:")
        print("                       `pipx inject etoro-tui keyring` or")
        print("                       `pip install etoro-tui[keyring]`)")
    print("  C.  Just print export commands. You set the env vars yourself.")
    print()
    options = ["a", "c"]
    if config.keyring_available():
        options.insert(1, "b")
    while True:
        try:
            choice = input(f"Choose [{'/'.join(options).upper()}]: ").strip().lower() or "a"
        except (EOFError, KeyboardInterrupt):
            print()
            return 1
        if choice in options:
            break
        print(f"  (please enter one of: {', '.join(options)})")
    print()

    if choice == "a":
        path = _write_envfile(pk, uk)
        print(f"  ✓ Wrote {path} (mode 600)")
    elif choice == "b":
        try:
            config.keyring_save(pk, uk)
        except Exception as e:  # noqa: BLE001 — keyring backends raise diverse errors
            print(f"  ✗ Keyring save failed: {e}", file=sys.stderr)
            print("    Falling back to ~/.etoro-tui/.env")
            path = _write_envfile(pk, uk)
            print(f"  ✓ Wrote {path} (mode 600)")
        else:
            print("  ✓ Saved to system keyring (service: etoro-public-key /")
            print("    etoro-user-key, account: etoro-api)")
    else:  # choice == "c"
        print("  Add to your shell profile (~/.zshrc or ~/.bashrc):")
        print(f'    export ETORO_PUBLIC_KEY="{pk}"')
        print(f'    export ETORO_USER_KEY="{uk}"')
        print("  Then `source ~/.zshrc` (or open a new shell).")
    print()

    _print_step(4, "Seed a TOML config (optional)")
    print(f"  ~/.etoro-tui/config.toml lets you customise the indices list,")
    print(f"  point at local data sources, and tune refresh cadences.")
    print()
    if _yes("Seed it from docs/config.example.toml?", default=True):
        seeded = _seed_config_toml()
        if seeded is not None:
            print(f"  ✓ Wrote {seeded}")
        elif config.CONFIG_TOML.exists():
            print(f"  (already exists — left alone) {config.CONFIG_TOML}")
        else:
            print("  (example template not found — skipped)")
    print()

    print("=" * 60)
    print("  Done. Run `etoro-tui` to launch.")
    print("  Tip: `etoro-tui --demo` shows the UI without any API call.")
    print("=" * 60)
    return 0
